### ISSUE TITLE
pull replication stops by BAD ATTACHMENT error [1.3.1-90]

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#1063]
I'm getting some warnings in my logs soon after my app starts and then the continuous pull replication process appears to stop.  Here's a snippet from the logs: https://gist.github.com/npomfret/b88e799d0cb4722702cdd458d5c76af2

**Comment by hideki** [comment]
@npomfret 

Do you mention about following messages?
```
01-18 12:25:22.674 12513-12585/? W/Database: Failed to get attachments for {de12b7c9-34ac-4632-9f1d-7ecb8c20767f #4-c2634703d2c1bd2c741d16aabc8900d5 @0}
01-18 12:25:22.674 12513-12585/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@41e8de50: failed to write {de12b7c9-34ac-4632-9f1d-7ecb8c20767f #5-286715a2921993c9a4fc83367e3a903f @2}: status=491
01-18 12:25:22.674 12513-12585/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, 4870f}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException
```

Don't you observe these message if you are using `1.4-8`?
http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-lite-android-master/

**Comment by hideki** [comment]
@npomfret 
Do you use sqlite or forestdb as a storage?

**Comment by npomfret** [comment]
I don't use forest db.  I'll downgrade to 1.4-8 and see if it improves.

**Comment by npomfret** [comment]
I went back to 1.4-8 and then 1.4-3 but it's still not working.  Here are some more logs: https://gist.github.com/npomfret/176b5c806e28f01325a2f3c589144f3f

You can see this eventually:

`D/Sync: State transition: STOPPING -> STOPPED (via STOP_IMMEDIATE).  this: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, 18ebd}`

**Comment by npomfret** [comment]
I spoke too soon, after deleting the DB and starting again it worked for a while but pull replication has again stopped working.  Again, no exception stack trances to be seen in logcat.   But I do see this shortly because it ends:

```
W/Sync: com.couchbase.lite.replicator.PullerInternal$9@42008cb8: failed to write {4b01039e-aaa8-45f8-b442-29f5e379fb1d #10-54e9e2e77ba509a6e47fa6a9b3bf7722 @2}: status=491

W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, 2bdf0}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException

```

**Comment by hideki** [comment]
@npomfret 

To print StackTrace, following line should be.
```java
Log.w(Log.TAG_SYNC, "%s: Progress: set error = %s",throwable, this, throwable);
```

Can you compile CBL Android by yourself? If so, can you try above change?

**Comment by npomfret** [comment]
For an unknown reason I cannot launch my app in debug mode on this device that has the problem.  Would it be possible for you to do a sweep of the code base and fix up the exception handling?  I'll be able to deploy and test the app quickly

**Comment by hideki** [comment]
@npomfret
`setError()` method is frequently called. So I don't enable to print stacktrace. Instead, I implemented `toString()` for `RemoteRequestResponseException`.  Logging should include code, message, and userInfo if it is applicable.
https://github.com/couchbase/couchbase-lite-java-core/issues/1570

**Comment by hideki** [comment]
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.4-30/

**Comment by npomfret** [comment]
Was that build supposed to fix the logging?  I'm still seeing

```
W/Sync: com.couchbase.lite.replicator.PullerInternal$9@398adf3e: failed to write {c2e27b22-a876-449c-9b95-bde2a08b3db1 #20-b99e2309fc62c35442bf39e68e58168e @4}: status=491

W/Sync: PullerInternal{http://192.168.1.64:4986/sync_gateway, pull, c06db}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
```

... no stack trace.  Would it be possible do a sweep of the log lines to make sure that stack traces are being logged.  Without them it's very hard to diagnose what's going on.

**Comment by npomfret** [comment]
It's possible that the document that's causing this error was removed from a users channel and subsequently re-added.  Could this be the cause of the problem?

**Comment by hideki** [comment]
The server does not return the attachment with its document because the attachment is same with the parent revision's attachment. CBL tries to load the attachment information from parent revisions, but CBL can not find the attachment information from parents revisions that are locally stored in the database.

Can you reproduce this issue with an emulator? If so, you could extract SQLite file from the emulator and check parent revision's JSON body values.

**Comment by hideki** [comment]
You can use `Android Device Monitor` to obtain files from the emulator.

1. Run `Android Device Monitor`
2. Select the device
3. Select `File Explorer` tab
4. Go to `/data/data/<your app id>/files`
5. Select Couchbase Lite Database file
6. Click top-right corner `pull the file from device` button

<img width="1100" alt="screen shot 2017-02-04 at 12 01 33 pm" src="https://cloud.githubusercontent.com/assets/15889/22621171/b8ccbc14-ead1-11e6-9c8c-23a50330fdae.png">

**Comment by npomfret** [comment]
This is frustrating.  When I click on the top level data dir nothing happens, as if its empty.  Then a minute or two later the Device Monitor application crashes.

**Comment by npomfret** [comment]
Also, I don't think this is only a problem with 1.4x - I've downgraded my clients to 1.3 and its still happening.

**Comment by hideki** [comment]
@npomfret,
Currently, I am not sure what causes this problem. Can you provide the test sync gateway URL for debugging?

**Comment by npomfret** [comment]
The url is `https://pomochat-sg-write-dev.pomocorp.com/sync_gateway`, and you can use this session `SyncGatewaySession=b86f31786e225674424b2f1594d478f16de9c734; path=/sync_gateway; domain=localhost; Max-Age=2678399; Expires=Thu, 09-Mar-2017 09:11:59 GMT'.`

**Comment by hideki** [comment]
It seems URL is not accessible with the given SyncGatewaySession value.
```
$ curl -X GET -H "Cookie: SyncGatewaySession=b86f31786e225674424b2f1594d478f16de9c734" "https://pomochat-sg-write-dev.pomocorp.com/sync_gateway"
<a href="/sync_gateway/">Moved Permanently</a>.
$ 
```

**Comment by npomfret** [comment]
Sorry, there's a trailing '/' missing:

```
curl -X GET -H "Cookie: SyncGatewaySession=b86f31786e225674424b2f1594d478f16de9c734" "https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/"
{"committed_update_seq":669431,"compact_running":false,"db_name":"sync_gateway","disk_format_version":0,"instance_start_time":1486307636226406,"purge_seq":0,"state":"Online","update_seq":669431}
```

**Comment by hideki** [comment]
Still I can not access.
```
$ curl -X GET -H "Cookie: SyncGatewaySession=b86f31786e225674424b2f1594d478f16de9c734" "https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/"
{"error":"Unauthorized","reason":"Login required"}
```

**Comment by npomfret** [comment]
That's strange, that session was supposed to be valid for a month.

Try this one please:

`SyncGatewaySession=712763d6b6f7c0bd5e20c82997c4490200844f5e; path=/sync_gateway; domain=localhost; Max-Age=2678399; Expires=Fri, 10-Mar-2017 16:58:02 GMT`

**Comment by hideki** [comment]
It works! Thank you.
```curl
curl -X GET -H "Cookie: SyncGatewaySession=712763d6b6f7c0bd5e20c82997c4490200844f5e; path=/sync_gateway; domain=localhost; Max-Age=2678399; Expires=Fri, 10-Mar-2017 16:58:02 GMT" -H "Cache-Control: no-cache" -H "Postman-Token: b0bf2f96-3db5-050c-03bc-3c3e587688a7" "https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/"
```
```json
{"committed_update_seq":670519,"compact_running":false,"db_name":"sync_gateway","disk_format_version":0,"instance_start_time":1486307636226406,"purge_seq":0,"state":"Online","update_seq":670519}hideki@hidekis:~$ 
```

**Comment by npomfret** [comment]
Any thoughts on this?  My app is completely broken without replication working.  

When I start the app from stratch it's fine.  But after a while this error happened and it never recovers.  It's not a 1.4 thing as I reported (I've renamed this issue), but 1.3.1-90.

I have a suspicion its caused my documents containing attachments that are being removed from a users channel (in order to save space on devices).  At a later date those document may be added back into the same users channel.  I think this is where the error happens - but can't prove it yet.

It doesn't happen with the iOS implementation.

**Comment by hideki** [comment]
Because of resource limitation, we could not investigate this issue so far.

**Comment by hideki** [comment]
Hi @npomfret,
SyncGatewaySession does not work again. Can you provide new session?
```
$ curl -X GET -H "Cookie: SyncGatewaySession=712763d6b6f7c0bd5e20c82997c4490200844f5e; path=/sync_gateway; domain=localhost; Max-Age=2678399; Expires=Fri, 10-Mar-2017 16:58:02 GMT" -H "Cache-Control: no-cache" -H "Postman-Token: b0bf2f96-3db5-050c-03bc-3c3e587688a7" "https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/"
{"error":"Unauthorized","reason":"Login required"}
$
```

**Comment by npomfret** [comment]
Here's a new session id: b77434c2b5d99cf62ab162dbf6783f553a71fe9b

I don't understand why these sessions are ceasing to work, they should be valid for a month.

**Comment by npomfret** [comment]
@hideki I've tried to address some of the logging problems: https://github.com/couchbase/couchbase-lite-java-core/pull/1600

**Comment by npomfret** [comment]
Ok, I've managed to get it to go wrong in the emulator, and I've pull the sql lite file(s) from it.  What's next?

**Comment by hideki** [comment]
Hi @npomfret 

I run the pull replication against `https://pomochat-sg-write-dev.pomocorp.com/sync_gateway`. I could successfully pull replicate all 9423 changes. I used the latest code, which is equivalent with 1.4-44. 
```
02-21 15:24:28.384 2699-2713/com.couchbase.lite.test E/Issue1063Test: changed() PULL replication event. Source: Replication{https://pomochat-sg-write-dev.pomocorp.com/sync_gateway, pull} Transition: RUNNING -> IDLE Total changes: 9423 Completed changes: 9423
```

You mentioned in the previous comment, you use or used 1.3.1-90. Can you simply migrate to the latest build, 1.4-44 which is release candidate build for 1.4.0.

Thanks!

**Comment by npomfret** [comment]
Ok, i tried 1.4-44.

On a local environment running on my laptop it feels no better.  One shot replication still fails and exits, and still no exceptions (can we move this https://github.com/couchbase/couchbase-lite-java-core/pull/1600 forward?). 

Here the log: https://gist.github.com/npomfret/0d83cfe3abf3e0707c802cb6e18c413f

I think it only goes wrong because my database has got itself in a certain state which yours won't be in.

**Comment by hideki** [comment]
Following is errors from your logs. I can not reproduce the BAD_ATTACHMENT (491) error.

```
02-21 18:45:12.226 9104-9736/com.pomochat W/Sync: PullerInternal{http://192.168.1.64:4986/sync_gateway, pull, ad78d}: Progress: set error = java.io.InterruptedIOException: thread interrupted

02-21 18:45:12.152 9104-9734/com.pomochat W/Sync: PullerInternal{http://192.168.1.64:4986/sync_gateway, pull, ad78d}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
```

**Comment by hideki** [comment]
@npomfret Can you apply your PR to your locally built module, and capture log message?

Also, You could query CBL source code with keyword: `Status.BAD_ATTACHMENT`, then print the information.

**Comment by hideki** [comment]
> can we move this couchbase/couchbase-lite-java-core#1600 forward?

We can not print the StackTrace for all errors.

**Comment by npomfret** [comment]
Do you have any instructions on how to build CBL locally so I can apply my code?

> We can not print the StackTrace for all errors.

Of course you can!  But you've decided not to, which I understand although don't agree with.  By withholding stack trace information from your users you are making it extremely difficult to diagnose errors (just look at what you're asking me to do).  I believe that the presents of a stack trace does not indicate an error.  It's the presents of an error that indicates an error.  If you users don't want to see stack traces for warnings then they should adjust their log level.

I've suggested a compromise which I didn't get a reply to which is to double log: continue to log the warnings and errors without the stack information (in some cases), and log the stack trace at VERBOSE level as a second line of logging.  

As a side note, I couldn't see an consistency with your logging.  Sometimes (mostly) you print the stack trace, sometimes you toString() the exception:

            } catch (Exception e) {
                Log.e(Log.TAG_SYNC, "%s Exception in checkSessionAtPath()", this, e);
            }

and sometimes neither:

```
        } catch (NoSuchMethodException msme) {
            try {
                String errorMessage = String.format(Locale.ENGLISH, "Router unable to route request to %s", message);
                Log.w(TAG, errorMessage);

```
Do you have any guidelines as when to do what?

**Comment by hideki** [comment]
> Do you have any instructions on how to build CBL locally so I can apply my code?

- https://github.com/couchbase/couchbase-lite-android#building-couchbase-lite-on-command-line-via-gradle

If you would like to build your app with CBL as submodule
- https://github.com/couchbase/couchbase-lite-android/wiki/Add-Couchbase-Lite-to-your-project-as-a-submodule

> Anyway, do you have any guidelines as when to do what?

Sorry, currently no guideline for the logging.

**Comment by npomfret** [comment]
I just couldn't get this working.  I'm getting a duplicate class problem.

`> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/couchbase/lite/AsyncTask.class

I've no idea where the duplicate class is coming from.  Been trying for hours now and am going to have to give up.

I think I may have a work around which is to repeatedly perform a one-shot pull replication.  If it throws an exception, just do it again.  I think eventually it passes and from that point the continuous replication will work.  The problem is I've not idea how long it will work for, but for now thats all I've got right now.  I do appreciate the help you've provided.

I can't get my PR accepted.  I guess you guys really don't want to see exceptions, even at verbose level logging, I just can't understand why.  Stack traces only provide information, and your API has a pretty serious bug in it which stops apps from working. Without the exception stack traces i can't help you to find it.  With respect, the logging and exception handling in this codebase isn't perfect.  It's inconsistent, incomplete in my opinion, simply wrong (in places), sometimes you don't  propagate exceptions and so the root cause is lost. Adding stack traces and propagating properly would provide some clues to this and future problems.  I think logging the stack traces at verbose level is a good compromise, I'm happy to make the change as long as it's agreed first.

Also, I have a copy of the database taken from an emulator as you suggested, but I've no idea what to do with it??

**Comment by npomfret** [comment]
Unfortunately my workaround doesn't work after all.  

Here's another couple of screen shots of the debugger, I hope they can spread some light on the problem.  I'm quite sure this is something to do with document that contains attachments which is getting removed from a users `_changes` feed and subsequently re-added (the document, not the attachment).  I think I have proof here:

So the document _6358..._ has an attachment and 2 revisions (_4-6ccd..._ and _3-29a5..._), If looks like the `forceInsert` method is creating an `ancestry` list, which is of length 1 containing just one revision _3-29a5..._, and not the _head_ revision.

Then `processAttachmentsForRevision`is calling `outStatus.setCode(Status.BAD_ATTACHMENT)` at line 1137 because both `_parentAttachments` is null **and** the `findAttachment` method returned null (see screen shot below).  

Now, the reason for `findAttachment` returning null is that it's using `attachment.getRevpos()` to search the `ancestry`.  The `ancestry` however only contains 1 item (_3-29a5..._) but the attachment's `revpos` field is set to 2 - so it's looking for index 2 of a 1 item list, which makes sense (I guess).

But, the reason for `_parentAttachments` being null might is because the parent revision (_3-29a5..._) has a `_removed` flag - here it is in the debugger:

![screen shot 2017-02-25 at 11 11 56](https://cloud.githubusercontent.com/assets/5489469/23330665/66ef585e-fb4b-11e6-8941-5c7529382faa.png)

You can see there are no attachments in its body, so calling `getProperties().get("_attachments")` on this `RevisionInternal` object will return `null`.  

**The parent revision doesn't have the attachment because it is in a removed state**.  I think this is the source of the bug.  The next line of code (`processAttachmentsForRevision`) cannot cope with there being no attachments in the parent revision and throws a `CouchbaseLiteException` with status `Status.BAD_ATTACHMENT`.  

All this gets caught (but not logged) in `insertDownloads`, which calls `setError(new RemoteRequestResponseException(e.getCBLStatus().getCode(), null));` (and doesn't propagate the exception).  And finally, the call to `setError` kills the replication (and also doesn't log the stack) because it is deemed a _PermanentError_:

            if (Utils.isPermanentError(this.error) || !isContinuous()) {
                triggerStopGraceful();
            }

And so replication irrevocably ends and there's no way to get it started again.

Here are a couple more screen shots showing the debugger at different points during the crash.

![screen shot 2017-02-25 at 10 57 08](https://cloud.githubusercontent.com/assets/5489469/23330594/875a42ea-fb49-11e6-8bf3-b28fc0bdfcfa.png)

![screen shot 2017-02-25 at 10 58 37](https://cloud.githubusercontent.com/assets/5489469/23330599/8f6aa1dc-fb49-11e6-9ed9-2cc8939c2162.png)

**Comment by npomfret** [comment]
Having given it some thought, I suspect (but haven't tried yet) that you could reproduce it, something like:

1. Make sure the client is switched off (or at least NOT replicating)
2. Create a document that will appear in the client's `_changes` feed (_rev:1_)
3. Add an attachment to it (_rev:2_)
4. Modify the document so that it is removed from the client's `_changes` feed (_rev:3_)
5. Purge revisions 1 and 2, leaving only the _removed_ revision (_rev:3_)
6. Modified the document again so that it once again appears in the client's `_changes` feed (_rev:4_)
7. Turn on the client and perform a pull replication.

Possibly you turn on the client between steps 5 and 6 (after the purge) instead of 7, I'm not sure.

**Comment by hideki** [comment]
Hi @npomfret,

Thank you for your further investigation. We will look into it.

Thanks,
Hideki

**Comment by hideki** [comment]
Note to self:

Push replication had the similar problem.
https://github.com/couchbase/couchbase-lite-java-core/issues/1471

**Comment by hideki** [comment]
Hi @npomfret,
Can you provide the valid SG session ID to investigate the issue?

**Comment by npomfret** [comment]
`SyncGatewaySession=8075a826651d07904084f0e76aeab6e919e82888; path=/sync_gateway; domain=pomochat-sg-write-dev.pomocorp.com; Max-Age=431999; Expires=Fri, 03-Mar-2017 11:53:55 GMT`

**Comment by hideki** [comment]
Hi @npomfret,

Did you delete the document, `6358006e-61bb-4e11-a059-224e82628e59` that you faced the problem?


```
$ curl -X GET -H "Cookie: SyncGatewaySession=8075a826651d07904084f0e76aeab6e919e82888" -H 'Accept: application/json' 'https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/6358006e-61bb-4e11-a059-224e82628e59'
{"error":"not_found","reason":"missing"}
$
```

**Comment by npomfret** [comment]
Ah, no - the log was taken from my internal dev system, not the one I've pointed you to.

There's no shortage of examples though, here's a snippet of the log from a device connected to this environment.  I think they are all due to the same problem:

```
02-26 20:01:14.773 13347-13464/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@4210b218: failed to write {f0c096bf-88ed-4949-9b3b-6210cde759c4 #4-1d7c58b99525a18ec3a9f5b9b46aaa27 @24}: status=491
02-26 20:01:14.773 13347-13464/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, 468e3}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
02-26 20:01:14.773 13347-13464/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, 468e3} [fireTrigger()] => STOP_GRACEFUL
02-26 20:01:14.778 13347-13464/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@4210b218: failed to write {f0c271f6-fbc0-4b40-a646-0f6458cf92ec #4-114010ff288df30c3b87d712bf11bed1 @25}: status=491
02-26 20:01:14.778 13347-13464/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, 468e3}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
02-26 20:01:14.778 13347-13464/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, 468e3} [fireTrigger()] => STOP_GRACEFUL
02-26 20:01:14.788 13347-13464/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@4210b218: failed to write {20bd11f7-4e2c-44d5-8fed-465fe6031ce3 #4-db6133162174475621c5a4be5b45412e @26}: status=491
02-26 20:01:14.788 13347-13464/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, 468e3}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}

02-26 20:01:18.298 13347-13485/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@421a31a0: failed to write {62e895d1-2344-423c-910d-f9e31696d99b #4-98d214614a075cbe8ab89286b1d27888 @2}: status=491
02-26 20:01:18.303 13347-13485/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
02-26 20:01:18.303 13347-13485/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6} [fireTrigger()] => STOP_GRACEFUL
02-26 20:01:18.328 13347-13485/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@421a31a0: failed to write {1a94e1ff-917f-49cf-ae9e-a5daf6f8b04b #4-683374b3fc48e34d70f92873ecbfe65a @3}: status=491
02-26 20:01:18.328 13347-13485/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
02-26 20:01:18.328 13347-13485/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6} [fireTrigger()] => STOP_GRACEFUL
02-26 20:01:18.333 13347-13485/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@421a31a0: failed to write {9a60161c-5bcc-4caf-8442-e9d5ae4bd5ff #4-55dd4c767a346c77c563d4ecdc389f4f @4}: status=491
02-26 20:01:18.333 13347-13485/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
02-26 20:01:18.333 13347-13485/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6} [fireTrigger()] => STOP_GRACEFUL
02-26 20:01:18.338 13347-13485/? W/Database: Failed to get attachments for {3b176db0-402c-4d7d-9b98-144420a85bfe #5-cf256f4cf8806cb46e3e27d0d21201e8 @0}
02-26 20:01:18.343 13347-13485/? W/Database: Failed to get attachments for {3b176db0-402c-4d7d-9b98-144420a85bfe #4-1f8f5b8352dcb202d750e4c599b02caa @0}
02-26 20:01:18.343 13347-13485/? W/Database: Failed to get attachments for {3b176db0-402c-4d7d-9b98-144420a85bfe #5-cf256f4cf8806cb46e3e27d0d21201e8 @0}
02-26 20:01:18.343 13347-13485/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@421a31a0: failed to write {3b176db0-402c-4d7d-9b98-144420a85bfe #6-50371d9b37a64f00e8ddee3016982cca @5}: status=491
02-26 20:01:18.343 13347-13485/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
02-26 20:01:18.343 13347-13485/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6} [fireTrigger()] => STOP_GRACEFUL
02-26 20:01:18.348 13347-13485/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@421a31a0: failed to write {5ec87e55-3f23-42e7-8072-84276a38b8e3 #4-921dd53560646c063f2b51a3a22c0b83 @6}: status=491
02-26 20:01:18.348 13347-13485/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
02-26 20:01:18.348 13347-13485/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6} [fireTrigger()] => STOP_GRACEFUL
02-26 20:01:18.358 13347-13485/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@421a31a0: failed to write {32c958d8-0b45-4f24-b7fc-02fafcc1dc42 #4-d02aaaafa75cd53c2e474bb906bca8e3 @7}: status=491
02-26 20:01:18.358 13347-13485/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
02-26 20:01:18.358 13347-13485/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6} [fireTrigger()] => STOP_GRACEFUL
02-26 20:01:18.363 13347-13485/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@421a31a0: failed to write {ff0b9d52-134e-4363-b4d6-2351b9010bc7 #4-fb588ae6bed27eadaa13613dde8014a0 @8}: status=491
02-26 20:01:18.363 13347-13485/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
02-26 20:01:18.363 13347-13485/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6} [fireTrigger()] => STOP_GRACEFUL
02-26 20:01:18.368 13347-13485/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@421a31a0: failed to write {6c77186b-fdaa-49b0-acde-0ec20c189b17 #4-0ab5f1fed6373add1f984ba495f007f4 @9}: status=491
02-26 20:01:18.373 13347-13485/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}
02-26 20:01:18.373 13347-13485/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6} [fireTrigger()] => STOP_GRACEFUL
02-26 20:01:18.378 13347-13485/? W/Sync: com.couchbase.lite.replicator.PullerInternal$9@421a31a0: failed to write {db934cbe-d9cf-40ff-b99c-1b4cb5ef6863 #4-b4de63b80ea79cc48489e4227591a480 @10}: status=491
02-26 20:01:18.378 13347-13485/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, fc6e6}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=491}

```

**Comment by hideki** [comment]
Hi @npomfret,
Can you call `GET /{db}/{docID}` REST API with document `6358006e-61bb-4e11-a059-224e82628e59`, and paste the ressponse here?

**Comment by npomfret** [comment]
{
  "owner": "7f3b03b8-340d-4d41-80f9-d4ebec187216",
  "_attachments": {
    "low-res": {
      "digest": "sha1-FovLOQW4UDz0LrgYbPBOJ7hvtgs=",
      "length": 42943,
      "stub": true,
      "content_type": "image/jpeg",
      "revpos": 2
    }
  },
  "readers": [
    "95ee00f0-6f24-4553-8228-d045c4b4289d",
    "86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3",
    "9133f13f-c7d9-41ae-a09f-37cdf906160b"
  ],
  "audit": {
    "user_id": "admin",
    "client_timestamp_utc": "2017-02-21T23:11:21.164Z"
  },
  "_sync": {
    "time_saved": "2017-02-21T23:11:21.477600613Z",
    "sequence": 774541,
    "rev": "6-50371d9b37a64f00e8ddee3016982cca",
    "history": {
      "channels": [
        [
          "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216",
          "ch_private_95ee00f0-6f24-4553-8228-d045c4b4289d"
        ],
        [
          "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216"
        ],
        [
          "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216"
        ],
        [
          "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216",
          "ch_private_86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3",
          "ch_private_95ee00f0-6f24-4553-8228-d045c4b4289d"
        ],
        [
          "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216",
          "ch_private_86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3",
          "ch_private_95ee00f0-6f24-4553-8228-d045c4b4289d"
        ],
        [
          "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216",
          "ch_private_86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3",
          "ch_private_9133f13f-c7d9-41ae-a09f-37cdf906160b",
          "ch_private_95ee00f0-6f24-4553-8228-d045c4b4289d"
        ]
      ],
      "revs": [
        "4-1f8f5b8352dcb202d750e4c599b02caa",
        "5-cf256f4cf8806cb46e3e27d0d21201e8",
        "3-7d1402b0b446fb6f4d20132669f85d5b",
        "1-4a4a35297e1835a61d196f05f4ae83d8",
        "2-b8b668f691db301b25e23b3df316df67",
        "6-50371d9b37a64f00e8ddee3016982cca"
      ],
      "parents": [
        2,
        0,
        4,
        -1,
        3,
        1
      ]
    },
    "channels": {
      "ch_private_95ee00f0-6f24-4553-8228-d045c4b4289d": null,
      "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216": null,
      "ch_private_86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3": null,
      "ch_private_9133f13f-c7d9-41ae-a09f-37cdf906160b": null
    },
    "recent_sequences": [
      475434,
      475435,
      510755,
      674152,
      730982,
      774541
    ]
  },
  "chat_message_id": "750373457f35b9d104e76eba6d18ec85",
  "chat_group_id": "-Xw0NKiv0nmz_TuciRbxNt7",
  "type": "attachment",
  "client_timestamp_utc": "2016-07-11T17:32:13Z"
}

**Comment by npomfret** [comment]
FYI - i got a 404 with `6358006e-61bb-4e11-a059-224e82628e59`

**Comment by npomfret** [comment]
@hideki  Have you have any luck reproducing the problem?

**Comment by hideki** [comment]
@npomfret 
As you wrote before, the attachment is associated with the older revision. In this case, revision 2 (revpos: 2). Also from your debugging information, error occurs because CBL client can not find revision 2 which has the attachment.
```json
  "_attachments": {
    "low-res": {
      "digest": "sha1-FovLOQW4UDz0LrgYbPBOJ7hvtgs=",
      "length": 42943,
      "stub": true,
      "content_type": "image/jpeg",
      "revpos": 2
    }
  },
```


I have one more request. Can you provide /{db}/_changes REST API response from Sync Gateway for this document? I'd like to know if SG returns revision 2 (`2-b8b668f691db301b25e23b3df316df67`).

**Comment by npomfret** [comment]
Looks like that one has been modified a few times since:

`,{"seq":774541,"id":"3b176db0-402c-4d7d-9b98-144420a85bfe","changes":[{"rev":"6-50371d9b37a64f00e8ddee3016982cca"}]}`

Here's another example using `62e895d1-2344-423c-910d-f9e31696d99b` (from the logs above):

```
{
  "owner": "7f3b03b8-340d-4d41-80f9-d4ebec187216",
  "_attachments": {
    "low-res": {
      "digest": "sha1-vd6GsdBR8PWjrLYrg/VfvnbUXq4=",
      "length": 103415,
      "stub": true,
      "content_type": "image/jpeg",
      "revpos": 2
    }
  },
  "readers": [
    "95ee00f0-6f24-4553-8228-d045c4b4289d",
    "d76004d2-c307-4984-a666-6efc047f5eca",
    "86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3"
  ],
  "audit": {
    "user_id": "admin",
    "client_timestamp_utc": "2017-02-21T23:11:21.161Z"
  },
  "_sync": {
    "time_saved": "2017-02-21T23:11:21.345037236Z",
    "sequence": 774533,
    "rev": "4-98d214614a075cbe8ab89286b1d27888",
    "history": {
      "channels": [
        [
          "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216",
          "ch_private_86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3",
          "ch_private_95ee00f0-6f24-4553-8228-d045c4b4289d"
        ],
        [
          "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216",
          "ch_private_86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3",
          "ch_private_95ee00f0-6f24-4553-8228-d045c4b4289d"
        ],
        [
          "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216"
        ],
        [
          "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216",
          "ch_private_86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3",
          "ch_private_95ee00f0-6f24-4553-8228-d045c4b4289d",
          "ch_private_d76004d2-c307-4984-a666-6efc047f5eca"
        ]
      ],
      "revs": [
        "1-d844c5610e754bebdbdd9625e4d9f24e",
        "2-d194efcd0b7ff8049526b3959bd28d0d",
        "3-941a133aa4b4afcf5d7c2c25cf70ab04",
        "4-98d214614a075cbe8ab89286b1d27888"
      ],
      "parents": [
        -1,
        0,
        1,
        2
      ]
    },
    "channels": {
      "ch_private_95ee00f0-6f24-4553-8228-d045c4b4289d": null,
      "ch_private_7f3b03b8-340d-4d41-80f9-d4ebec187216": null,
      "ch_private_86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3": null,
      "ch_private_d76004d2-c307-4984-a666-6efc047f5eca": null
    },
    "recent_sequences": [
      467584,
      467585,
      508669,
      774533
    ]
  },
  "chat_message_id": "03b87971-d744-4ca3-a423-2c27b9dba179",
  "chat_group_id": "-nZaP_8vgz_1kpW8PEX_QnL",
  "type": "attachment",
  "client_timestamp_utc": "2016-07-28T11:45:51Z"
}
```

`,{"seq":774533,"id":"62e895d1-2344-423c-910d-f9e31696d99b","changes":[{"rev":"4-98d214614a075cbe8ab89286b1d27888"}]}`

**Comment by hideki** [comment]
Hi @adamcfraser,

In the scenario, the document is updated like @npomfret explained below, should Sync Gateway returns `_attachment` with `follow: true` instead of `stub: true`?

Comment from @npomfret 
----------------------
Having given it some thought, I suspect (but haven't tried yet) that you could reproduce it, something like:

1. Make sure the client is switched off (or at least NOT replicating)
2. Create a document that will appear in the client's `_changes` feed (_rev:1_)
3. Add an attachment to it (_rev:2_)
4. Modify the document so that it is removed from the client's `_changes` feed (_rev:3_)
5. Purge revisions 1 and 2, leaving only the _removed_ revision (_rev:3_)
6. Modify the document again so that it once again appears in the client's `_changes` feed (_rev:4_)
7. Turn on the client and perform a pull replication.

Possibly you turn on the client between steps 5 and 6 (after the purge) instead of 7, I'm not sure.
----------------------

**Comment by npomfret** [comment]
@hideki @adamcfraser have you guys managed to reproduce this?  My app is completely dead and totally unusable - a fix would really be appreciated!

**Comment by npomfret** [comment]
@hideki @adamcfraser - this has gone very quiet.  Can we get a fix in 1.4?

**Comment by hideki** [comment]
Hi @npomfret,

From the information you provided, I believe CBL behaves as expected. CBL is implemented that CBL aborts the replication if the attachment does not exist. 

I recommend you to file the ticket to the sync gateway git repository to get the attention from SG engineers. https://github.com/couchbase/sync_gateway/issues

**Comment by npomfret** [comment]
But the android app replication crashes and my app stops working, that can't be right!  The iOS app copes with it.

**Comment by hideki** [comment]
I might misunderstand you. Do you observe CBL Android crash instead of stopping the pull replicator?

**Comment by npomfret** [comment]
No, the app doesn't crash.  Replication crashes, well it stops and won't start again (that's probably a better description).  Ether way, surely this can't be seen as not a bug in the android code.  Ios deals with it.

How can you be certain it's a sync gateway bug?  Can you comment on #2374 ?

**Comment by hideki** [comment]
>  well it stops and won't start again

This is expected behavior as `BAD_ATTACHMENT (491)` is treated as a permanent error. So stopping the replicator is correct behavior. And after restarting the replicator, the replicator will stop again because the replicator will face same data again.

> Ios deals with it.

How does CBL iOS behave for this scenario?

> How can you be certain it's a sync gateway bug?

I am not sure if this is sync gateway bug. The response from sync gateway you shared is to cause `BAD_ATTACHMENT` error with CBL Android.

**Comment by hideki** [comment]
Hi @npomfret ,

We need two information from you.
- Step 5 below Purge: Where purge occurs at CBL Android? or at Sync Gateway, or other devices?
- We need HTTP request and response data between client and Sync Gateway. I believe you could reproduce this issue with your local environment. Please capture it by HttpScoop or Charles? 

```
npomfret commented 11 days ago • edited
Having given it some thought, I suspect (but haven't tried yet) that you could reproduce it, something like:

1. Make sure the client is switched off (or at least NOT replicating)
2. Create a document that will appear in the client's _changes feed (rev:1)
3. Add an attachment to it (rev:2)
4. Modify the document so that it is removed from the client's _changes feed (rev:3)
5. Purge revisions 1 and 2, leaving only the removed revision (rev:3)
6. Modify the document again so that it once again appears in the client's _changes feed (rev:4)
7. Turn on the client and perform a pull replication.

Possibly you turn on the client between steps 5 and 6 (after the purge) instead of 7, I'm not sure.
```

**Comment by npomfret** [comment]
Ios continues to replicate.  If its not a bug in CBL android, feature parity with iOS would be nice. They should both die horribly in an unrecoverable mess.  Just kidding, obviously, I would prefer the android version to behave like the iOS one. 

And if it's not a bug in CBL android, and it's not a bug in the sign gateway, what is the solution?  Manipulating the data in the way is not invalid, but it kills the client completely.  And there's no workaround.

I can't say this clearly enough - **this software does not work in the scenario described**.  I can't believe that you anyone would think this acceptable.

**Comment by npomfret** [comment]
> Step 5 below Purge: Where purge occurs at CBL Android? or at Sync Gateway, or other devices?

Just to be clear, these steps are a guess at how to reproduce it based on what I could gather from the debugging steps shown in the images above.  And I would guess that the purge happens on the sync-gateway.

**Comment by npomfret** [comment]
WRT the http traffic. It'll take me some time to get that data, mostly because I've no idea what HttpScoop or Charles are.  But I'm sure I can figure it out.

But has anyone there even tried to reproduce this yet?

**Comment by hideki** [comment]
Note to self:

possible reproduction steps. Need to write test case or small app to reproduce this.
```
[3:57 PM] Adam Fraser: 1. Create doc in local (rev-1)
2. Add attachment in local (rev-2)
3. Push to Sync Gateway
4. Update doc on Sync Gateway to move out of user's channel
5. Client pulls doc from server, gets removal notification (rev-3)
[3:57 PM] Adam Fraser: (continuing...)
[3:58 PM] Adam Fraser: 6. Purge rev-1 and rev-2 on client
7. Update doc on Sync Gateway to move back into user's channel (rev-4)
8. Client pulls rev-4 from server
[3:58 PM] Adam Fraser: I think the client will hit the issue at step 8
[3:59 PM] Adam Fraser: actually let me change step 8
[3:59 PM] Adam Fraser: 8. Pull replication gets rev-4 over changes feed
9. Pull replication attempts to get rev-4 (with atts_since=??)
[4:00 PM] Adam Fraser: just to clarify that I think it's #9 that's failing, not #8
```

**Comment by borrrden** [comment]
FYI It looks like iOS is specifically handling this case [here](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLRestPuller.m#L725-L729)

**Comment by hideki** [comment]
@npomfret 

> Ios continues to replicate. If its not a bug in CBL android, feature parity with iOS would be nice. They should both die horribly in an unrecoverable mess. Just kidding, obviously, I would prefer the android version to behave like the iOS one.

We put a lot of effort to make all platforms behave same. Based on information we shared here, iOS also stops to repricate. But, there might be some implementation difference between iOS and Android.

> I think maybe the fact that you asked the question means that I didn't write it clearly enough. The intention is to create the state on the sync gateway and not on the client. That's why step 1 reads "Make sure the client is switched off". You can't do the purge on the client because the client was be switched off and so won't have the data to purge.

I understood your comment as you explained. But we need clearification about this part.

> WRT the http traffic. It'll take me some time to get that data, mostly because I've no idea what HttpScoop or Charles are. But I'm sure I can figure it out.

Thanks for your helps

> But has anyone there even tried to reproduce this yet?

We will.

**Comment by hideki** [comment]
@borrrden You Rock!

**Comment by hideki** [comment]
Reference
- https://github.com/couchbase/couchbase-lite-ios/issues/1001
- https://github.com/couchbase/couchbase-lite-ios/commit/3e61ab2a1d62afb45a19c0c0958d72e5a126d4b5
- https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L594-L605

**Comment by hideki** [comment]
Applied same work around with iOS.
PR: https://github.com/couchbase/couchbase-lite-java-core/pull/1611

**Comment by hideki** [comment]
Hi @npomfret ,
`1.4-49`has workaround for BAD ATTACHMENT that is implemented for iOS too. Please try it.
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.4-49/

Thanks!

**Comment by npomfret** [comment]
@hideki @borrrden you guys indeed rock, thank you!  I've tested 1.4-49 and it behaves as expected.  I've tried both scenarios that I thought of to reproduce the problem and continuous pull replication continues to work. The attachments appear in my app as expected :)

Thanks again!

**Comment by hideki** [comment]
@npomfret,
I am curious how your app can access the attachment? Our solution is just a workaround to avoid the replication stop. Does the blob (attachment) file exist on the local disk?
Thanks!

**Comment by npomfret** [comment]
I was wondering that too.  The attachments are typically images, I think maybe the image API I use has cached them on disk.  I'll experiment and see if wiping the cache results in the images disappearing.

**Comment by npomfret** [comment]
Am I correcting in understanding that although the android code handles the situation more gracefully now there's still an outstanding bug here.  When the attachments come back they are still unobtainable due to the lack of history?

And if so would the same problem occur if a client decided to purge some attachments (in order to save space perhaps).  If those document got modified in the future and reappeared in the changes feed, would you run into the same problem?

**Comment by npomfret** [comment]
Hi - is there any plan to address this?

**Comment by tikimcfee** [comment]
@npomfret A huge thank you for your time and debugging with this issue. Your investigations here really helped our team. And of course, thanks to @hideki (et al!) for their support as well. 

I really want to give this a +1. I know there's a lot of active 2.0 work going on, but it would be great if some of these more fundamental changes could be patched in a final pre-2.0 release. 1.3.X-1.4.X were really undocumented and patchy in terms of who could use what and when. A release that includes this fix, @npomfret's question about the attachment itself, and other 'critical' issues would go a really long way in tiding the Android developer base until 2.0 hits a stable point.

**Comment by hideki** [comment]
Hi @npomfret and @tikimcfee,
Thank you for supporting Couchbase Lite. At this moment, we don't have the plan to release 1.4.x for the client library. This could be changed. Can you build the CBL by yourself from latest commit?

**Comment by tikimcfee** [comment]
@hideki Hello again!

Understandable. We can actually build from your branches, as we already have to do some light modifications (one in particular is giving the LoggerFactory a setter so we can intercept logs and write them out for support issues).
