### ISSUE TITLE
2.0: Forum: CouchBaseLite 2.0 Replication Error When multiple clients delete Documents

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1242]
Forum: https://forums.couchbase.com/t/couchbaselite-2-0-replication-error-when-multiple-clients-delete-documents/13341

> now ,I using ToDo Example(Couchbase lite 2.0 beta 011) to test Replication Items。i runing app on the multiple android devices, I found add\update items replication is okey.but when one client delete a document,the other client document does not change anything.i don't know what happened.

**Comment by hideki** [comment]
REF: https://github.com/couchbaselabs/mobile-training-todo/issues/144

**Comment by rajagp** [comment]
Did some investigation : 
This issue occurs even with Couchbase-lite-iOS. (i.e Deletions from the app are not going through).
This is the error reported by the SG (using the todo-config.json file)
```
2017-07-05T13:51:52.177-04:00 Sync+: Inserting rev "user1.6E398F3F-6B63-4A42-BB30-064CAC3A9D98" 2-3b145348adc408cb6c426a0a0858380eb3c1a5f0 history="", array = []string{"2-3b145348adc408cb6c426a0a0858380eb3c1a5f0"}
2017-07-05T13:51:52.178-04:00 CRUD+: Invoking sync on doc "user1.6E398F3F-6B63-4A42-BB30-064CAC3A9D98" rev 2-3b145348adc408cb6c426a0a0858380eb3c1a5f0
2017-07-05T13:51:52.179-04:00 WARNING: Sync fn exception: TypeError; doc = map[_id:user1.6E398F3F-6B63-4A42-BB30-064CAC3A9D98 _rev:2-3b145348adc408cb6c426a0a0858380eb3c1a5f0 _deleted:%!s(bool=true)] -- db.(*Database).getChannelsAndAccess() at crud.go:1049
2017-07-05T13:51:52.179-04:00 Sync: MSG#18    --> 500 Exception in JS sync function

```

DELETEs directly through the Admin REST API on SG work fine

**Comment by hideki** [comment]
@rajagp, Thank you very much for your further investigation. Log message said `500 Exception in JS sync function`. Can you identify why sync function fails?

**Comment by tleyden** [comment]
> DELETEs directly through the Admin REST API on SG work fine

There is a slightly different code path for the blip protocol handling.  From the type error, it might mean that in the doc passed to the sync funtion, it had "true" (string) instead of `true` (boolean)

@sethrosetter do you know if there are any cblite 2.0 tests that are close to this that could be adapted to possibly repro?

**Comment by snej** [comment]
LiteCore sets the `_deleted` property to a boolean `true` (not the string `"true"`.)

The document contents shown in the Go error seem to say that `_deleted` is a bool value; isn't that what the `%!s` means?
`Sync fn exception: TypeError; doc = map[_id:user1.6E398F3F-6B63-4A42-BB30-064CAC3A9D98 _rev:2-3b145348adc408cb6c426a0a0858380eb3c1a5f0 _deleted:%!s(bool=true)]`

So since the cause is a JS error in the sync function, has anyone looked at the sync function?

**Comment by snej** [comment]
The SG BLIP replication code doesn't do anything with the `_deleted` property.
The sync function in ToDo does reference `doc._deleted` a lot, but not in any way that could produce a TypeError.

**Comment by rajagp** [comment]
So I tried with a different config file - one with a simpler sync function that does nothing but channel("public") (and I gave user1 access to public1 channel under "users")  .  I logged in as "user1" on both clients (I have Android and iOS app running)
With that change, I don't see the type error on the SG when I delete from client1 . In fact I do see a replication progress update notification on client 2  . However, the live query listener does not get called back (as DB does not get updated for whatever reason).  [Creation of doc does get synchronized to all clients so I know replication and routing works OK. So only deletions don't]

**Comment by hideki** [comment]
It seems there is the problem in SG codes.
REF: https://github.com/couchbase/sync_gateway/issues/2713

**Comment by snej** [comment]
This should be fixed now, with some changes to LiteCore. You'll just need to update the submodule.

**Comment by hideki** [comment]
@snej Thank you!

**Comment by hideki** [comment]
Deleted document replication issue is still reproducible.

SG Version: 1.5.0-555
CBL Android: 2.0.0-DB016

CBL log
```
09-06 12:18:57.639 15496-15560/com.couchbase.todo E/C4Socket: C4Socket.callback.write() handle -> 0xb00e3ad0, allocatedData.length -> 175
09-06 12:18:57.646 15496-15643/com.couchbase.todo E/WebSocket: WebSocketListener.onMessage() bytes -> 0e020d03004854545000020035303000496e7465726e616c206572726f723a20454f46
09-06 12:18:57.646 15496-15643/com.couchbase.todo E/C4Socket: C4Socket.callback.completedReceive() socket -> 0x90f29930, byteCount -> 35
09-06 12:18:57.646 15496-15561/com.couchbase.todo I/LiteCore [Actor]: BLIP[->blip:10.17.1.69:4984/todo/_blipsync] performNextMessage
09-06 12:18:57.646 15496-15561/com.couchbase.todo I/LiteCore [Actor]: DB->blip:10.17.1.69:4984/todo/_blipsync performNextMessage
09-06 12:18:57.647 15496-15561/com.couchbase.todo I/LiteCore [Sync]: {6} now idle
09-06 12:18:57.647 15496-15563/com.couchbase.todo I/LiteCore [Actor]: Push->blip:10.17.1.69:4984/todo/_blipsync performNextMessage
09-06 12:18:57.647 15496-15561/com.couchbase.todo I/LiteCore [Actor]: Repl->blip:10.17.1.69:4984/todo/_blipsync performNextMessage
09-06 12:18:57.647 15496-15563/com.couchbase.todo E/LiteCore [Sync]: {7} Got error response to rev user1.c5261e10-fd00-4252-8d63-71a8a27e88cb #2-ed6c4df9ddd5785226ed5e0247d6ec56502f615d (seq 7): HTTP 500 'Internal error: EOF'
09-06 12:18:57.647 15496-15563/com.couchbase.todo I/LiteCoreJNI: [NATIVE] C4Replicator.documentErrorCallback() repl -> 0x0x9230d300, pushing, Internal error: EOF
09-06 12:18:57.647 15496-15563/com.couchbase.todo E/C4Replicator: documentErrorCallback() handle -> 2452673280, pushing -> true, docID -> user1.c5261e10-fd00-4252-8d63-71a8a27e88cb, domain -> 1, code -> 35, internalInfo -> 1004, trans -> false
09-06 12:18:57.651 15496-15564/com.couchbase.todo E/WebSocket: WebSocketListener.onMessage() bytes -> 17020d03004854545000020035303000496e7465726e616c206572726f723a20454f46
09-06 12:18:57.651 15496-15562/com.couchbase.todo I/LiteCore [Actor]: BLIP[->blip:10.17.1.69:4984/todo/_blipsync] performNextMessage
09-06 12:18:57.651 15496-15564/com.couchbase.todo E/C4Socket: C4Socket.callback.completedReceive() socket -> 0xb00e3ad0, byteCount -> 35
```

SG Log
```
2017-09-06T12:18:49.500-07:00 Sync: MSG#21 "setCheckpoint"
2017-09-06T12:18:49.500-07:00 Sync+: MSG#21    --> OK
2017-09-06T12:18:58.098-07:00 Sync: MSG#13! "changes"
2017-09-06T12:18:58.098-07:00 Sync: MSG#22! "changes"
2017-09-06T12:18:58.098-07:00 Sync: Received 1 changes from client
2017-09-06T12:18:58.098-07:00 Sync: Received 1 changes from client
2017-09-06T12:18:58.098-07:00 Sync+: MSG#22!    --> OK
2017-09-06T12:18:58.098-07:00 Sync+: MSG#13!    --> OK
2017-09-06T12:18:58.105-07:00 Sync: MSG#14 "rev"
2017-09-06T12:18:58.105-07:00 Sync: MSG#14    --> 500 Internal error: EOF
2017-09-06T12:18:58.112-07:00 Sync: MSG#23 "rev"
2017-09-06T12:18:58.112-07:00 Sync: MSG#23    --> 500 Internal error: EOF
2017-09-06T12:19:03.218-07:00 Sync: MSG#24 "setCheckpoint"
2017-09-06T12:19:03.218-07:00 Sync+: MSG#24    --> OK
```

**Comment by hideki** [comment]
We fixed this issue before, but we did not verify a fix. This issue is no longer reproducible with https://github.com/couchbase/couchbase-lite-android/commit/dbc436dc1fa807e80c004cbd16faa407aee1e7f8 and SyncGateway 2.0.0-748.
