### ISSUE TITLE
Replication-eventing listener is not able to catch errors thrown for conflicts

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1798]
Version: 2.5.0-90
Client OS: android
Server: CBS 6.5.0-1813

I'm working on testing the scenario "Replication Event - error". This what I'm trying to achieve for error-event.

```
 1. Create docs in CBL and replicate to SG using push one-shot replication
 2. Add update to SG and CBL to create conflict
 3. Add replication event listener for the replication and start push one-shot replication.
 4. Check the error is thrown in replication event changes
```

I can see the error thrown for conflict in app logs, but those errors are not registered on event listener.

This is the test I've written (code is not complete to validate all scenario for this test) - https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl2.5-replication-eventing/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication_eventing.py#L153

Logs -
Logs from python runner - 
[python_client_runner.log](https://github.com/couchbase/couchbase-lite-android/files/2693623/python_client_runner.log)

Logs for App from logical console - 
[android_console_logs.log](https://github.com/couchbase/couchbase-lite-android/files/2693624/android_console_logs.log)

**Comment by djpongh** [comment]
@hrajput89 , issue should be fixed. Can you verify?

**Comment by hrajput89** [comment]
I'm still seeing this issue. I tested this with build 2.5.0-109 for android and also on 2.5.0-132 for iOS.  I can see the docs are getting rejected with 409 but the event listener doesn't catch anything.


```
V/CouchbaseLite/REPLICATOR: {Push#11} Checkpoint now at #19
E/CouchbaseLite/REPLICATOR: {Push#11} Proposed rev 'push_cbl_docs_7' #2-fc0742fec32af773f630ea2b0758dd6fc2c27dcd (ancestor 1-f13540cb6827ac7b874cda4250275c37cc874014) rejected with status 409
I/CouchbaseLite/REPLICATOR: {Repl#10} documentEnded push_cbl_docs_7 2-fc0742fec32af773f630ea2b0758dd6fc2c27dcd flags=02 (6/409)
V/CouchbaseLite/REPLICATOR: {Push#11} Checkpoint now at #20
                            {Push#11} progress +4480/+0, 0 docs -- now 4480 / 4480, 0 docs
```

[android_console.log](https://github.com/couchbase/couchbase-lite-android/files/2754206/android_console.log)

**Comment by hrajput89** [comment]
I can see error code of 10409 for conflict in replication events. Hence closing the issue.
