### ISSUE TITLE
Replicator status says busy when SGW is offline

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-android#1867]
Android CBL version : 2.5.0-157
SGW version : 2.5.0-205

Steps to reproduce:
1. 1. Create 2 DBs and Create 1000 docs in CBL
        2. Do push replication to two SGS(each DB
        to each SG)  -> two replications repl1, repl2
         3. Wait until replication is done.
         3 stop both replicators
        3. exchange DBs of SG and do pull replication -> two replicatoins again, repl1, repl2
        4. Wait until replication is done
         5. Stop both replicators repl1, repl2
        4. stop one of the sync gateway (sg2)
        5. Start pull replication again and verify it throws error with 2nd replicator as sg2 is down.
        6. Verify one CBL DB should be successful
        other CBL DB should fail as associated Sg is down
         7. Stop both the replicators again

Actual : 
Replicator, repl2 fails which complains that replicator is busy/offline. 

Sometimes I see replicator is offline
Sometimes I see replicator is busy
and fails to stop 2nd replicator.

Expected : 
Replicator should stop

CBL logs : 
https://gist.github.com/sridevi-15/788bd94f42dda7c751a593d040f83c3f
Note : This happens with 1000 docs and sometimes 100 docs. With 10 docs it always works fine.
It is not consistent. One in 3 times fail.

**Comment by snej** [comment]
There are 159 LiteCore replicators being created during that log, all of them to remote database `sg_db1`. All of them seem to stop with Connection Refused. Looks like the CBL Replicator keeps trying to reconnect.

I didn't see any replicator being created on `sg_db2`. There is one occurrence of that string, but logged by an already-open socket object, so whatever replicator was replicating to it must have been started before this piece of the log.

**Comment by pasin** [comment]
Look like there is at least a race condition when accessing c4ReplStatus in stop() and retry(). From the code, it's not obvious.

**Comment by pasin** [comment]
Yes, I'm able to reproduce the issue.

**Comment by pasin** [comment]
It turns out my test was wrong and I was not able to reproduce the issue. Stopping the replicator did stop the replicator. However I found that there is a logging issue that logging messages from CBL replicator code didn't shown up in console. I will fix that first and will need to ask QE to rerun the test so that I could get the complete log.

**Comment by pasin** [comment]
@sridevi-15 Can you rerun the test with 2.5.0-178? I have fixed missing logging issue so that we could get the complete logs?

**Comment by sridevi-15** [comment]
Hi Pasin, I ran with 2.5.0-206 build. 
This is the cbl logs which I still see repl is busy
https://gist.github.com/sridevi-15/f60080df0830d6a538b0ed7600f5bb5f

**Comment by pasin** [comment]
@sridevi-15 From the log, I don't see that the test has called to stop the replicator when the replicator is being offline. Does the test check for offline status and stop the replicator? Could you please check?

**Comment by pasin** [comment]
Another thing, it seems like after offline, the replicator kept retrying every two seconds instead of retrying in exponential delay. I will look into this issue.

**Comment by pasin** [comment]
From the log, the issue is that returned c4status is `BUSY` (instead of STOPPED) but error is `Connection Refuse`. I couldn't reproduce this stage though.

```
CouchbaseLite Replicator Info: CBLReplicator[<* URL[ws://192.168.33.12:4984/sg_db2]]: Transient error (Connection refused); will retry in 2 sec...
CouchbaseLite Replicator Info: Reachability<192.168.33.12>: flags=2; starting...
CouchbaseLite Replicator Info: CBLReplicator[<* URL[ws://192.168.33.12:4984/sg_db2]] is offline, progress 0/0, error: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={NSLocalizedDescription=Connection refused}
CouchbaseLite Replicator Info: Reachability<192.168.33.12>: flags <-- 2
CouchbaseLite Replicator Info: CBLReplicator[<* URL[ws://192.168.33.12:4984/sg_db2]]: Retrying...
CouchbaseLite Database Info: {DB#187}==> litecore::SQLiteDataFile /Users/sridevi.saragadam/Library/Developer/CoreSimulator/Devices/7EC1CCC1-9C92-4C15-ADB9-81FA17AD02C3/data/Containers/Data/Application/F60956EF-21CF-411F-AD50-DB9CA6F33AD6/Library/Application Support/CouchbaseLite/cbl_db11551251350.77.cblite2/db.sqlite3 @0x600003cf6760
CouchbaseLite Database Info: {DB#187} Opening database
CouchbaseLite Network Info: {Connection#188}==> litecore::blip::Connection ->ws://192.168.33.12:4984/sg_db2/_blipsync @0x600002ba4210
CouchbaseLite Network Info: {Connection#188} Opening connection...
CouchbaseLite Replicator Info: {Repl#189}==> litecore::repl::Replicator /Users/sridevi.saragadam/Library/Developer/CoreSimulator/Devices/7EC1CCC1-9C92-4C15-ADB9-81FA17AD02C3/data/Containers/Data/Application/F60956EF-21CF-411F-AD50-DB9CA6F33AD6/Library/Application Support/CouchbaseLite/cbl_db11551251350.77.cblite2/ ->ws://192.168.33.12:4984/sg_db2/_blipsync @0x7f86b8901838
CouchbaseLite Replicator Info: {Repl#189} Pull=continuous, Options={{cookies:"SyncGatewaySession=8ef7d8ae213f1fb09b6b235ee828a21d0eac22e8", headers:{User-Agent:"CouchbaseLite/2.5.0 (Swift; iOS 12.0; iPhone) Build/206 Commit/519ae8ac+CHANGES LiteCore/2.5.0 (206)"}, progress:0}}
CouchbaseLite Replicator Info: CBLReplicator[<* URL[ws://192.168.33.12:4984/sg_db2]]: Starting backgrounding monitor...
CouchbaseLite Replicator Info: {Repl#189} activityLevel=connecting: connectionState=1
CouchbaseLite Replicator Verbose: {DBWorker#190}==> litecore::repl::DBWorker ->ws://192.168.33.12:4984/sg_db2/_blipsync @0x7f86b8902388
CouchbaseLite Replicator Verbose: {DBWorker#190} Checkpoint doc ID = cp-5yM0KDWsbwNOFbbZgGmVhTBeEIU=
CouchbaseLite Replicator Verbose: {DBWorker#190} Remote-DB ID 2 found for target <ws://192.168.33.12:4984/sg_db2/_blipsync>
CouchbaseLite Replicator Info: CBLReplicator[<* URL[ws://192.168.33.12:4984/sg_db2]] is connecting, progress 0/0, error: (null)
CouchbaseLite Network Info: <CBLWebSocket: 0x6000032b42c0> connecting to 192.168.33.12:4984...
CouchbaseLite Replicator Info: {DBWorker#190} activityLevel=idle: pendingResponseCount=0, eventCount=1, activeDocs=0
CouchbaseLite Replicator Info: CBLReplicator[<* URL[ws://192.168.33.12:4984/sg_db2]] is connecting, progress 0/0, error: (null)
CouchbaseLite Replicator Info: {Repl#189} Local checkpoint 'cp-5yM0KDWsbwNOFbbZgGmVhTBeEIU=' is [0, '321']; getting remote ...
CouchbaseLite Network Verbose: <CBLWebSocket: 0x6000032b42c0>: Checking for timeout in 16.000 sec
CouchbaseLite Replicator Verbose: {DBWorker#190} now idle
CouchbaseLite Replicator Info: {Repl#189} activityLevel=connecting: connectionState=1
CouchbaseLite Replicator Info: {Repl#189} pushStatus=stopped, pullStatus=busy, dbStatus=idle, progress=0/0
CouchbaseLite Replicator Info: {Repl#189} activityLevel=connecting: connectionState=1
[] nw_socket_handle_socket_event [C6:1] Socket SO_ERROR [61: Connection refused]
[] nw_connection_get_connected_socket [C6] Client called nw_connection_get_connected_socket on unconnected nw_connection
TCP Conn 0x600003008b40 Failed : error 0:61 [61]
CouchbaseLite Network Verbose: <CBLWebSocket: 0x6000032b42c0>: ErrorEncountered on <__NSCFInputStream: 0x6000037a0090>
CouchbaseLite Network Verbose: <CBLWebSocket: 0x6000032b42c0>: Disconnect
CouchbaseLite Network Info: CBLWebSocket CLOSED WITH ERROR: NSPOSIXError[61, "Connection refused"]
CouchbaseLite Network WARNING: {C4SocketImpl#191}==> litecore::repl::C4SocketImpl ws://192.168.33.12:4984/sg_db2/_blipsync @0x7f86b8901bf0
CouchbaseLite Network WARNING: {C4SocketImpl#191} Unexpected or unclean socket disconnect! (reason=errno, code=61)
CouchbaseLite Network Info: {C4SocketImpl#191} sent 0 bytes, rcvd 0, in 0.000 sec (nan/sec, nan/sec)
CouchbaseLite Network Verbose: C4Socket of <CBLWebSocket: 0x6000032b42c0> is being disposed
CouchbaseLite Network Verbose: DEALLOC <CBLWebSocket: 0x6000032b42c0>
CouchbaseLite Network Info: {Connection#188} Closed with errno 61: Connection refused
CouchbaseLite Replicator Info: {Repl#189} Connection closed with errno 61: "Connection refused" (state=1)
CouchbaseLite Replicator Info: {DBWorker#190} activityLevel=idle: pendingResponseCount=0, eventCount=1, activeDocs=0
CouchbaseLite Replicator Info: BLIP sent 0 msgs (0 bytes), rcvd 0 msgs (0 bytes) in 0.121 sec. Max outbox depth was 0, avg nan
CouchbaseLite Replicator ERROR: {Repl#189} Got LiteCore error: POSIX error 61 "Connection refused"
CouchbaseLite Replicator Verbose: {Repl#189} progress +0/+0, 0 docs -- now 0 / 0, 0 docs
CouchbaseLite Replicator Info: {Pull#192}==> litecore::repl::Puller ->ws://192.168.33.12:4984/sg_db2/_blipsync @0x7f86bb900708
CouchbaseLite Replicator Info: {Repl#189} activityLevel=stopped: connectionState=-1
CouchbaseLite Replicator Info: {Pull#192} activityLevel=busy: pendingResponseCount=0, _caughtUp=0, _waitingForChangesCallback=0, _pendingRevMessages=0, _activeIncomingRevs=0
CouchbaseLite Replicator Info: {Repl#189} now stopped
CouchbaseLite Replicator Verbose: {Pull#192} now busy
CouchbaseLite Replicator Info: {Repl#189} activityLevel=busy: connectionState=-1
CouchbaseLite Database Info: {DB#187} Closing database
CouchbaseLite Replicator Info: {Repl#189} now busy
CouchbaseLite Database Verbose: {DB#187} Pre-close housekeeping: 0 of 115 pages free (0%)
CouchbaseLite Replicator Info: Reachability<192.168.33.12>: stopped
CouchbaseLite Replicator Info: CBLReplicator[<* URL[ws://192.168.33.12:4984/sg_db2]] is busy, progress 0/0, error: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={NSLocalizedDescription=Connection refused}
CouchbaseLite Database Verbose: {DB#187} Closed SQLite database
CouchbaseLite Replicator Info: {Repl#189} activityLevel=stopped: connectionState=-1
CouchbaseLite Replicator Info: CBLReplicator[<* URL[ws://192.168.33.12:4984/sg_db2]] is busy, progress 0/0, error: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={NSLocalizedDescription=Connection refused}
CouchbaseLite Replicator Info: {Repl#189} now stopped
CouchbaseLite Replicator Info: CBLReplicator[<* URL[ws://192.168.33.12:4984/sg_db2]]: Transient error (Connection refused); will retry in 2 sec...
```

**Comment by pasin** [comment]
From the log above, it seems the activity level of the Repl#189 is `busy` instead of `stopped`.
```
CouchbaseLite Replicator ERROR: {Repl#189} Got LiteCore error: POSIX error 61 "Connection refused"
CouchbaseLite Replicator Verbose: {Repl#189} progress +0/+0, 0 docs -- now 0 / 0, 0 docs
CouchbaseLite Replicator Info: {Pull#192}==> litecore::repl::Puller ->ws://192.168.33.12:4984/sg_db2/_blipsync @0x7f86bb900708
CouchbaseLite Replicator Info: {Repl#189} activityLevel=stopped: connectionState=-1
CouchbaseLite Replicator Info: {Pull#192} activityLevel=busy: pendingResponseCount=0, _caughtUp=0, _waitingForChangesCallback=0, _pendingRevMessages=0, _activeIncomingRevs=0
CouchbaseLite Replicator Info: {Repl#189} now stopped
CouchbaseLite Replicator Verbose: {Pull#192} now busy
CouchbaseLite Replicator Info: {Repl#189} activityLevel=busy: connectionState=-1
CouchbaseLite Database Info: {DB#187} Closing database
CouchbaseLite Replicator Info: {Repl#189} now busy
```

This might not always happens as I could see from a part of the log that worked correctly:

```
CouchbaseLite Replicator ERROR: {Repl#177} Got LiteCore error: POSIX error 61 "Connection refused"
CouchbaseLite Replicator Info: BLIP sent 0 msgs (0 bytes), rcvd 0 msgs (0 bytes) in 0.204 sec. Max outbox depth was 0, avg nan
CouchbaseLite Replicator Verbose: {Repl#177} progress +0/+0, 0 docs -- now 0 / 0, 0 docs
CouchbaseLite Replicator Info: {Pull#180}==> litecore::repl::Puller ->ws://192.168.33.12:4984/sg_db2/_blipsync @0x7f86b8b02098
CouchbaseLite Replicator Info: {Repl#177} activityLevel=stopped: connectionState=-1
CouchbaseLite Replicator Info: {Pull#180} activityLevel=busy: pendingResponseCount=0, _caughtUp=0, _waitingForChangesCallback=0, _pendingRevMessages=0, _activeIncomingRevs=0
CouchbaseLite Replicator Info: {Repl#177} now stopped
CouchbaseLite Replicator Verbose: {Pull#180} now busy
CBLReplicator[<* URL[ws://192.168.33.12:4984/sg_db2]]: Transient error (Connection refused); will retry in 4 sec...
```

@snej What could cause the activity level of `Repl#189` to be busy instead of stopped?

**Comment by pasin** [comment]
@sridevi-15 The recent log provided above is iOS log not Android log. Could you please rerun the test with the latest android build and provide the log again? I have added more log to CBL Android so that we can understand more about the issue. Thanks.

**Comment by sridevi-15** [comment]
Hi Pasin, tested with 2.5.0-179 on android. 
Here is the cbl logs: 
https://gist.github.com/sridevi-15/afe5aec9d86e09484a484f26e921e94a

**Comment by pasin** [comment]
@sridevi-15 We have fixed BUSY with Error status issue. Please test with 2.5.0-183. 

Another thing is that from the log, I don't see the test server called to stop the replicator even when getting offline status. Please also double check the test code. Thanks.

**Comment by pasin** [comment]
@sridevi-15 Did the latest build fix the issue?

**Comment by sridevi-15** [comment]
I verified on ios - 2.5.0-224 and Android 2.5.0-184. Test has passed now.
