### ISSUE TITLE
Push replication and attachment

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-android#637]
We are creating a document and add the atachment. But push replication can not send it to the server. File size 1MB. Version 0.0.0-531

07-07 10:46:07.110: E/RemoteRequest(2714): io exception.  url: http://admin:admin@192.168.1.33:5984/qrbox-server/update_qrbox-qrboxe90c5183?new_edits=false
07-07 10:46:07.110: E/RemoteRequest(2714): org.apache.http.NoHttpResponseException: The target server failed to respond
07-07 10:46:07.110: E/RemoteRequest(2714): 	at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:85)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at com.couchbase.lite.support.RemoteMultipartRequest.run(RemoteMultipartRequest.java:48)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-07 10:46:07.110: E/RemoteRequest(2714): 	at java.lang.Thread.run(Thread.java:841)

**Comment by hideki** [comment]
Hi @QRPro,
Could you please share Sync Gateway version and configuration, and also the code snippet of setting the attachment?

**Comment by QRPro** [comment]
If the attachment size 1 byte, it work. If 500kb is not working.

Document document = getDatabase().getExistingDocument(documentId);
UnsavedRevision unsavedRevision = document.createRevision();
unsavedRevision.setAttachment(updateName, attachment.getContentType(), attachment.getContent());
unsavedRevision.save();

iOS version works fine. Push attachments.

Server version CouchDB 1.2.0

**Comment by hideki** [comment]
Hi @QRPro,

Attachment push replication to CouchDB was fixed for CBL 1.1.0 release.
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.1.0/

Please try 1.1.0 build?

**Comment by QRPro** [comment]
We have try 1.1.0. The error remained.

07-13 09:46:35.402: E/RemoteRequest(26044): org.apache.http.NoHttpResponseException: The target server failed to respond

**Comment by sergio91pt** [comment]
It could be CouchDB, according to [1], 1.2.0 is no longer a supported
release.

[1]: https://cwiki.apache.org/confluence/display/COUCHDB/Current+Releases

2015-07-13 5:48 GMT+01:00 QRPro <notifications@github.com>:

**Comment by QRPro** [comment]
Version couchbase for iOS working properly. I do not think that the case CouchDB 1.2.0.

**Comment by hideki** [comment]
Hi @QRPro 

I tested push replication with attachment against CouchDB 1.6.1 that I installed. It works fine.
Following is sample code.
https://github.com/hideki/couchbase-lite/tree/master/test/SimpleCouchDBClient

As @sergio91pt  wrote, it could be CouchDB 1.2.0 issue.

Thanks!

**Comment by snej** [comment]
@QRPro: Definitely upgrade CouchDB. There have been major improvements in attachment replication in the latest releases.
