### ISSUE TITLE
Compaction with any revision depth doesn't seem to do anything

### ISSUE THREAD

**Issue by tikimcfee** [couchbase/couchbase-lite-android#685]
Hey there guys,

Our team has a high priority on working with compaction of our databases on our mobile devices, and these last few days have seen a lot of tests on our part. Part of these tests were manually manipulating a single docs's attachments from a *server side implementation* to test how/if the compact() method would work, and it seems that through a manual database manipulation from a *server side implementation* of a doc's attachments, it did (i.e., the removal of one of the sha1's seemed to prompt the remove of the attachment .blob from disk).

However, now that we are attempting to automate this process, the attachments for old revisions do not seem to be removed from disk during compaction. In fact, it seems that compaction of the database does not actually yield any results. This may be due to some bug on our part, but we're not entirely sure.

We have used `database.setMaxRevTreeDepth(X);` to all sorts of values, but no matter the value (0, 1, 2, 5, 10, etc.), the end results are the same - the attachments that were on OLD revisions of documents stick around, and the database size remains unchanged.

Doing a little bit of step-through-debugging, I found the actual lines that seem to be responsible for pruning the DB:
`Database.java`
`pruneRevsToMaxDepth`
`lines : 5191-5196`

The toPrune hashMap that results for our current database during testing ends up at 3091 keys, and during the while loop, `database.delete("revs", "doc_id=? AND revid < ? AND current=0", deleteArgs);` never returns a non-zero value. Not exactly sure if that's a helpful symptom, but it was noticed.

Unfortunately, the next method, `garbageCollectAttachments()` then seems to have a File[] that contains every single attachment in the '_dbname_ attachments' directory, and doesn't delete any of them.

It's very possible I have a misunderstanding with how compaction affects a local device, insofar as modifying a document on a device to change the revision, setting a max depth, and then compact()'ing will not actually delete old revisions for docs without intervention from server. But, it's also possible there's a super subtle bug somewhere in the pruning code. In either scenario, I would absolutely appreciate some help and/or understanding on this. At the very least, it will help us to understand the toolset better!

A great many thanks for your time on this, again!

**Comment by hideki** [comment]
iOS unit test for Database.compact().
- https://github.com/couchbase/couchbase-lite-ios/blob/master/Unit-Tests/DatabaseAttachment_Tests.m#L172
- https://github.com/couchbase/couchbase-lite-ios/blob/master/Unit-Tests/DatabaseAttachment_Tests.m#L442

First make sure if CBL Android has above tests.

**Comment by MatFl** [comment]
We seem to be stuck on the same issue. In our app a document is updated quite often. During the day a few thousand revisions will be created for this document. No matter what MaxRevTreeDepth is set to, the database delete method (Database.java line 5194) always returns 0 ( we did debug it down to the native call).

The jsons of the old revisions get removed though.

Having multiple thousands of revisions for the documents has a major impact on the performance. Do you guys have a schedule for the 1.2.0 release?

**Comment by hideki** [comment]
Hi @MatFl,

Coucbhase Lite Android/Java v1.1.0, the maximum revision tree depth is the maximum value of integer. It prevents `compact()` method to delete old revisions.

```private static final int DEFAULT_MAX_REVS = Integer.MAX_VALUE;```
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/Database.java#L74

Could you please try to set max value around 20 by calling `Database. setMaxRevTreeDepth()`
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/Database.java#L831

Sorry for slow reply, I had misunderstood the problem till I re-readed the v1.1.0 source code. Hope this helps you.

Thanks,
Hideki

**Comment by hideki** [comment]
Hi @tikimcfee,

If my memory is correct, your dataset has many conflicting branch. Conflicted branch's leaf nodes are not deleted if its current value is 1 (active). If conflicted branch is unused from the app, please try to delete conflicted leaf node with using following API before calling `compact()` method?

`List<SavedRevision>  Document.getConflictingRevisions()`
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/document/document/index.html#savedrevision-conflictingrevisions--get-

`SavedRevision SavedRevision.deleteDocument()`
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/revision/saved-revision/index.html#savedrevision-deletedocument

Thanks,
Hideki

**Comment by MatFl** [comment]
Hi @hideki,

In our case `setMaxRevTreeDepth` is set to 10. But we still have many thousand revisions a day which do not get deleted when calling `compact()`.

Should the Database not even prevent that many revisions when the maxRevTree Value is set?

Here is a screenshot of the `revs` table right after calling `compact()`. As you can see there still are a lot of unused revisions.
![screenshot from 2015-11-23 08 07 03](https://cloud.githubusercontent.com/assets/8408624/11331341/9d46351e-91b9-11e5-8269-c10999447f97.png)

**Comment by hideki** [comment]
Hi @MatFl,
From the v1.1.0 source codes, I can not figure out why old revisions are not deleted. Could you please write all detail information to reproduce the problem. We will try to reproduce the problem.
Thanks!

**Comment by MatFl** [comment]
Hi @hideki ,

As you say, the source looks ok. I debugged through it and the problem seems to be, that the actual delete command (Database.java line 5194):
`int rowsDeleted = database.delete("revs", "doc_id=? AND revid < ? AND current=0", deleteArgs);` always returns 0. Could it be a SQLite issue?

I wrote this small test to replicate it:

```java
package com.test.couchbasetest;

import android.test.AndroidTestCase;

import com.couchbase.lite.CouchbaseLiteException;
import com.couchbase.lite.Database;
import com.couchbase.lite.Document;
import com.couchbase.lite.Manager;
import com.couchbase.lite.QueryOptions;
import com.couchbase.lite.QueryRow;
import com.couchbase.lite.UnsavedRevision;
import com.couchbase.lite.android.AndroidContext;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;

public class ApplicationTest extends AndroidTestCase {

    private static final int DOC_COUNT = 10;
    private static final int REV_COUNT = 30;

    public void testRevPruning() throws IOException, CouchbaseLiteException {
        final Manager manager = new Manager(new AndroidContext(getContext()), Manager.DEFAULT_OPTIONS);

        final Database database = manager.getDatabase("test");
        database.setMaxRevTreeDepth(20);

        for (int j = 0; j < DOC_COUNT; j++) {
            final Document document = database.createDocument();
            for (int i = 0; i < REV_COUNT; i++) {
                final String value = "rev " + i;
                document.update(new Document.DocumentUpdater() {
                    @Override
                    public boolean update(final UnsavedRevision newRevision) {
                        newRevision.getProperties().put("key", value);
                        return true;
                    }
                });
            }

            assertEquals(REV_COUNT, document.getRevisionHistory().size());
        }

        database.compact();

        final Map<String, Object> allDocs = database.getAllDocs(new QueryOptions());
        final ArrayList<QueryRow> rows = (ArrayList) allDocs.get("rows");
        for (final QueryRow row : rows) {
            assertEquals(1, row.getDocument().getRevisionHistory().size()); // fails with size REV_COUNT
        }
    }
}
```

If you look into the database afterwards you will see the same as in my screenshot above.

**Comment by hideki** [comment]
Hi @MatFl,
Thank you very much your test codes.  We could reproduce the problem.

**Comment by hideki** [comment]
Hi @MatFl and @tikimcfee
I fixed this issue and sent PR for master branch. If you need fix for v1.1.0, can you apply https://github.com/couchbase/couchbase-lite-java-core/pull/828/files, and build by yourself?
Thanks!

**Comment by MatFl** [comment]
Thanks for the quick fix. We don't have a release schedule yet, so I don't think it is necessary to build it on my own.

It would be great to have nightly or alpha builds from the master branch though (#696)

**Comment by dbauduin** [comment]
Hello everybody,

I think there is still an issue with compaction. I have set the maximum depth of a document's revision tree to 1 and indeed, there is only one revision for each document. However, the size of the database file (cblite2) is unchanged. Worse, for each update of a document, the file size increases. I often update documents and the database file reaches 2 GB in only few days (for only 345 small documents in it), this is really a huge problem.

For information, I tried the SQLite storage type and everything is OK with this mode, the size of the database file doesn't increase on a document update.

**Comment by hideki** [comment]
@dbauduin,

- For information, I tried the SQLite storage type and everything is OK with this mode, the size of the database file doesn't increase on a document update.

Do you have issue with forestdb?

**Comment by dbauduin** [comment]
@hideki Yes, the size of the local forestdb file never decrease, even after a purge of documents or by limiting the number of revisions of documents. However, with SQLite mode the size of the file (. cblite2) decreases as expected.

**Comment by hideki** [comment]
ATTN: @hisundar 
Is there any known issue with forestdb compaction?
Thanks!

**Comment by hideki** [comment]
It seems fix is already in forestdb. Next time we migrate forestdb version, the issue should be fixed.
https://github.com/couchbaselabs/cbforest/issues/112
https://github.com/couchbase/couchbase-lite-ios/issues/1497

**Comment by dbauduin** [comment]
Ok thanks!
I think this issue is related: [couchbase/couchbase-lite-ios#1413](https://github.com/couchbase/couchbase-lite-ios/issues/1413).
