### ISSUE TITLE
Exception from forestDB during updateIndexes()

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#810]
```
03-15 16:25:55.604 5342-5391/com.sparkup.device E/Query: Exception caught in runAsyncInternal
   com.couchbase.lite.CouchbaseLiteException: ForestException{domain=2, code=-39}, Status: -39 (HTTP 500 Internal error)
       at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:283)
       at com.couchbase.lite.View.updateIndexes(View.java:321)
       at com.couchbase.lite.View.updateIndex(View.java:294)
       at com.couchbase.lite.Database.queryViewNamed(Database.java:2092)
       at com.couchbase.lite.Query$2.run(Query.java:483)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
    Caused by: ForestException{domain=2, code=-39}
       at com.couchbase.cbforest.Indexer.iterateDocuments(Native Method)
       at com.couchbase.cbforest.Indexer.iterateDocuments(Indexer.java:18)
       at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:250)
       at com.couchbase.lite.View.updateIndexes(View.java:321) 
       at com.couchbase.lite.View.updateIndex(View.java:294) 
       at com.couchbase.lite.Database.queryViewNamed(Database.java:2092) 
       at com.couchbase.lite.Query$2.run(Query.java:483) 
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment]
Note to self:
It seems multi-threading issue.
```
        /**
         * DB handle is being used by another thread. Forestdb handles must not be
         * shared among multiple threads.
         */
        int FDB_RESULT_HANDLE_BUSY = -39;
```

**Comment by orenyodfat** [comment]
I guess this exception happened in the case there is an extensive writes to the database while there are push replications in the background.

**Comment by mtrakal** [comment]
Get the same error on another lines:

```
com.couchbase.lite.CouchbaseLiteException: ForestException{domain=2, code=-39}, Status: -39 (HTTP 500 Internal error)
at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:283)
at com.couchbase.lite.View.updateIndexes(View.java:321)
at com.couchbase.lite.View.updateIndex(View.java:294)
at com.couchbase.lite.Database.queryViewNamed(Database.java:2055)
at com.couchbase.lite.Query.run(Query.java:433)

```
```
compile 'com.couchbase.lite:couchbase-lite-android:0.0.0-618'
compile 'com.couchbase.lite:couchbase-lite-android-forestdb:0.0.0-618'
```

**Comment by hideki** [comment]
Hi @orenyodfat and @malarky,

Could you please provide more detailed information? How doe you call query? from multiple threads? Also how many views that your app has? Do they have same prefix name?

Thanks!

**Comment by zgramana** [comment]
@snej please review with @hideki

**Comment by snej** [comment]
C4Indexer doesn't lock the mutexes of the C4Views it's indexing, so there is potential for the views to be called from multiple threads. I'll fix that.

**Comment by snej** [comment]
I have a PR in CBForest that may fix this; it adds some missing thread safety to C4Indexer (as mentioned above) and also to C4QueryEnumerator.

**Comment by hideki** [comment]
From code point of view, PR looks fine. 
Once CBL Android/Java adapts the latest master branch of cbforest (https://github.com/couchbase/couchbase-lite-java-core/issues/1057), I will run unit test with `fix/view_thread_safty`. Then I will merge this PR.

**Comment by hideki** [comment]
Fixed in cbforest.  
PR: https://github.com/couchbaselabs/cbforest/pull/75

**Comment by seshachalam-imaginea** [comment]
```
Exception caught in runAsyncInternal
                                                                 com.couchbase.lite.CouchbaseLiteException: ForestException{domain=2, code=-39}, Status: -39 (HTTP 500 Internal error)
                                                                     at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:283)
                                                                     at com.couchbase.lite.View.updateIndexes(View.java:321)
                                                                     at com.couchbase.lite.View.updateIndex(View.java:294)
                                                                     at com.couchbase.lite.Database.queryViewNamed(Database.java:2057)
                                                                     at com.couchbase.lite.Query$2.run(Query.java:483)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                  Caused by: ForestException{domain=2, code=-39}
                                                                     at com.couchbase.cbforest.Indexer.iterateDocuments(Native Method)
                                                                     at com.couchbase.cbforest.Indexer.iterateDocuments(Indexer.java:18)
                                                                     at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:250)
```

This is still occurring when using forestdb (not happening with sqlite) 
```
compile 'com.couchbase.lite:couchbase-lite-android:1.2.1'
compile 'com.couchbase.lite:couchbase-lite-android-forestdb:1.2.1'
```

**Comment by hideki** [comment]
Hi @seshachalam-imaginea,

Thank you very much for reporting the bug.

With 1.2.1, CBL Android/Java has multi-threading issue with ForestDB storage. 

We fixed multi-threading issue between view/query and other database operation.
If you have time, could you please try 1.3.0-43 build, which is RC for 1.3.0?
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.3.0-43/
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android-forestdb/1.3.0-43/

If 1.3.0-43 does not solve the issue you encounter,  could you please try 1.3.0-45 build ,which has fix of concurrent multiple queries issue with ForestDB. 
Note: fix for 1.3.0-45 will not be in 1.3.0, this should be in next version.
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.3.0-45/
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android-forestdb/1.3.0-45/

Thanks!
Hideki

**Comment by seshachalam-imaginea** [comment]
Will try with both the versions and update here. When will this 1.3.x be released ?

**Comment by hideki** [comment]
1.3.0 will be released soon if no release blocking issue is not found by then.

**Comment by seshachalam-imaginea** [comment]
I have not seen this issue with 1.3.0-43. thanks
