### ISSUE TITLE
Duplicate docs in Android view

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#855]
I have a basic view:

    function(doc) {
        if (doc.type === 'public-profile') {
          emit(doc.owner, null);
        }
      }

And occasionally I get multiple entires in it for a single document id.  If I query the view with _include_docs=true_ I can see that the duplicate entires have different __rev_ values.  It doesn't happen on IOS, and forcing my client to re-index by replacing the design doc makes the duplicates go away.

**Comment by hideki** [comment]
Hi @npomfret,
I believe this is same issue with https://github.com/couchbase/couchbase-lite-java-core/issues/1098.
Does your app have multiple views with same prefix?
Thanks!

**Comment by npomfret** [comment]
'Does your app have multiple views with same prefix?' - yes, well at least one of them does.

**Comment by hideki** [comment]
Can you try the build from master branch to verify the fix?
http://latestbuilds.hq.couchbase.com/couchbase-lite-android/0.0.0/0.0.0-688/

**Comment by prasannakumark** [comment]
Hi Hideki,
Very good news!!!, but i think some files are missing in that zip file, i am getting error here "cannot resolve symbol 'AndroidContext' ", means that in that library i could not able to find the AndroidContext class Or else i should change my code as per master branch 
https://github.com/couchbase/couchbase-lite-android/tree/master/src/main/java/com/couchbase/lite/android
  or any CBL API changes has been done. Please let know the how i can solve that problem and if you need information/clarifications.

Thank's
Prasanna Kumar

**Comment by hideki** [comment]
Hi @prasannakumark,

AndroidContext.class should be in classes.jar in couchbase-lite-android-0.0.0-688.aar. Did you add couchbase-lite-android-0.0.0-688.aar into your project?

**Comment by prasannakumark** [comment]
Hi @hideki,

Thank you, now it is working fine and also this bug is fixed!! but mean while i am facing very big issue relating to push replication, i made changes in some of the documents and also i created some documents but it is not pushing to server with any information. I think push replication issue. I've tested using this libraries http://latestbuilds.hq.couchbase.com/couchbase-lite-android/0.0.0/0.0.0-688/. Please let know the how i can solve that problem and if you need information/clarifications.

Thanks
Prasanna Kumar

**Comment by hideki** [comment]
Hi @prasannakumark,
Could you please file new ticket for push replication issue?
Any detailed information helps us a lot.

**Comment by hideki** [comment]
It seems 0.0.0-688 fixed this issue. I will close this ticket. If issue is still reproducible, please reopen the ticket.

**Comment by npomfret** [comment]
When will this fix get released? I've tested 1.2.1 and get the same behaviour - it makes my app unusable

**Comment by npomfret** [comment]
I've tested with 1.2.1 and its not fixed.  I'm not able to reopen this ticket (should I create another one?). 

It's very easy to reproduce, just make a change to any document thats in a index. Query the index and you'll see multiple revisions of the document. It happens 100% of the time.

**Comment by hideki** [comment]
Hi @npomfret,

None of stable build includes fix for this issue. 
Please try the build from latest master. 
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-710/

Thanks!

**Comment by MatFl** [comment]
This fix should have made it into 1.2.1. We already skipped 1.2.0 because of all the issues and now the bug fix release doesn't include the needed fixes. Waiting for 1.3.0 it is then...

**Comment by npomfret** [comment]
When do you think 1.3 will be released?  This bug is killing my app - its simply not possible to edit a document without causing all sorts of problems.

Should we reopen the ticket (I'm not allowed)?

**Comment by hideki** [comment]
1.3 release will be few month away. We are discussing about 1.2.2 release as another bug fix release.

@npomfret 
Is this issue still reproducible with 0.0.0-710? If yes, I will reopen this ticket.

**Comment by npomfret** [comment]
Yes it's still reproducible with 710

**Comment by npomfret** [comment]
Has there been any progress on this issue?

**Comment by bpolanec** [comment]
Hi all,
same happening here (Android), we reverted to 1.1.0 until this is fixed. This bug is a showstopper, any info on when fix will be released?

**Comment by hideki** [comment]
Hi @bpolanec,
Your issue might be same with https://github.com/couchbase/couchbase-lite-android/issues/795. Could you please try http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-710/ ?
Thanks!

**Comment by hideki** [comment]
@npomfret Sorry this ticket is still in the queue.

**Comment by npomfret** [comment]
I appreciate you guys are busy but is there any way to get this bumped up the queue?  I see it as quite a serious bug that affects all users who have views and modify documents in those views, which I imagine is almost everyone, no?  It makes my app totally unusable, possibly others also.

**Comment by hideki** [comment]
Hi @npomfret,

I wrote the test for this scenario. https://github.com/couchbase/couchbase-lite-android/commit/52616b1cec4098d99532cd8f288b6ae16715fe3c However, I could not reproduce the problem. I need more information to reproduce the issue.

Could you please provide more detailed information? If possible, could you please provide test codes or sample app?

Thanks,
Hideki

**Comment by MatFl** [comment]
Did you run this test with ForestDB or SQLite? I only have this issue with ForestDB.

**Comment by hideki** [comment]
@MatFl 
As default, unit tests are run with both ForestDB and SQLite.

**Comment by npomfret** [comment]
I have the issue using SQLite.  I don't have a test or sample app for you right now, but it is very easy to reproduce.

1. Create a view to index a doc.
2. Add a doc... check its in the view.
3. Someone else makes a modification to the doc.
4. (You get an update, via the sync gateway)
5. Query the view.  You now have 2 entires for 1 doc.

I'm using the REST api in CBL to query the view.

Doesn't happen on IOS, its an android bug only.

**Comment by hideki** [comment]
Hi @seth,
Can you implement above scenario with functional test?
Thanks!

**Comment by npomfret** [comment]
If you can point me towards your test suite I might be able to help

**Comment by hideki** [comment]
Hi @seth,

@npomfret is original reporter of this issue. He could help you to write test case.

@npomfret.
https://github.com/couchbaselabs/mobile-testkit is repository for our functional test which is managed by QE team.

I just submitted test scenario. You could add additional information if I am missing something.
https://github.com/couchbaselabs/mobile-testkit/pull/502

Thanks!

**Comment by sethrosetter** [comment]
@hideki @npomfret Thanks!

**Comment by gerbenupinion** [comment]
We're having the same issue here.

Is there a way to force a rebuild of a view? Then we could implement a ugly workaround in our own code until this issue is fixed.

**Comment by npomfret** [comment]
Hi @sethrosetter - i'm struggling to find time to learn how to write your tests.  Did you manage to reproduce the problem without one yet?

**Comment by hideki** [comment]
Hi @gerbenupinion ,
Your issue might be same with #795. Could you please try http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-710/ ?
Thanks!

**Comment by sethrosetter** [comment]
@npomfret I am working on a reproduction now.

**Comment by npomfret** [comment]
I have tried v710, it didn't fix the problem.

**Comment by hideki** [comment]
Hi @npomfret,
I believe you are using CBL with react-native. How do you integrate CBL libraries into react-native? With gradle dependency? I'd like to make sure if you also use 0.0.0-710 couchbase-lite-java-core jar file. http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-java-core/0.0.0-710/ .

**Comment by npomfret** [comment]
Yes, using gradle.  The react-native binding I use is here: https://github.com/couchbaselabs/react-native-couchbase-lite

To try out 0.0.0-710 I modified this [build](https://github.com/couchbaselabs/react-native-couchbase-lite/blob/master/android/build.gradle) file.

**Comment by hideki** [comment]
@npomfret, thank you for your response.

**Comment by jamiltz** [comment]
@npomfret I did a quick test app with the rn plugin to try to repro the issue https://github.com/jamiltz/react-native-couchbase-lite/tree/repro-cbl-android-855

Can you take a look; the view emits every doc that has the test_doc property. You can run it on two emulators, setup sync gateway with `adb reverse tcp:5984 tcp:5984` on each emulator and update the record on either emulator. I couldn't repro the issue, the query output is always 1 row with the latest revision. http://cl.ly/473c1x1D1g2f/Screen%20Shot%202016-06-10%20at%2013.29.08.png

**Comment by npomfret** [comment]
Ok, I'll start from scratch - which version of CBL should I test with?  And just to make sure I don't make a mistake could you show exactly what the gradle file should look like.

**Comment by jamiltz** [comment]
You should use 0.0.0-710 if you can still repro the issue with it. The build.gradle should contain the following in the `dependencies` section.
```
 compile 'com.couchbase.lite:couchbase-lite-android:0.0.0-710'
compile 'com.couchbase.lite:couchbase-lite-java-listener:0.0.0-710'
compile 'com.couchbase.lite:couchbase-lite-java-javascript:0.0.0-710'
```

**Comment by sethrosetter** [comment]
I have implemented the following test - https://github.com/couchbaselabs/mobile-testkit/blob/82d972e3a5d35cf2065e1cbd3755b742f6c3d57f/testsuites/listener/shared/client_sg/view_indexing.robot#L27-L103. 

You can view the steps here - https://github.com/couchbaselabs/mobile-testkit/blob/82d972e3a5d35cf2065e1cbd3755b742f6c3d57f/testsuites/listener/shared/client_sg/view_indexing.robot#L32-L41

I am unable to repro with 0.0.0-710. I am directly issuing rest calls against the listener. Am I missing a step or two possibly?

**Comment by npomfret** [comment]
Ok, some good news.  I retested and couldn't reproduce it on 0.0.0-710.  Maybe my previous test i was using an already corrupted database. Apologies, and thanks for looking into this.

Could someone else verify??

I did not 2 other things though.  Firstly an NPE that happened as soon as I edited the document:

```
E/Router: com.couchbase.lite.router.Router$4@528f7e58: Exception inserting revisions in bulk
                                                      java.lang.NullPointerException
                                                          at com.couchbase.lite.router.Router$4.run(Router.java:1328)
                                                          at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:705)
                                                          at com.couchbase.lite.router.Router.do_POST_Document_bulk_docs(Router.java:1286)
                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:525)
                                                          at com.couchbase.lite.router.Router.start(Router.java:555)
                                                          at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
                                                          at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
                                                          at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
                                                          at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
                                                          at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
                                                          at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
                                                          at java.lang.Thread.run(Thread.java:841)
```

Subsequent edits did not result in this error.

And secondly, when querying a view using the `keys` parameter, if that array is empty I now seem to get back all docs in the view.  Before I think it was returning no docs, which is what I'd expect.

**Comment by hideki** [comment]
Hi @npomfret,

I am glad to hear the build 0.0.0-710 can address the duplicated query result issue.

Could you please file new tickets for new incidents?

Thanks!
